Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '代號', 'text', 'sitid', '基金公司代號(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '名稱', 'text', 'cname', '基金公司中文名稱(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '英文名稱', 'text', 'ename', '基金公司英文名稱(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '成立日期', 'date', 'IncopratedDate', '成立日期(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '董事長', 'text', 'chairman', '基金公司董事長(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '電話', 'text', 'phone', '基金公司電話(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '傳真', 'text', 'fax', '基金公司傳真(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 80 , '統一編號', 'text', 'Com_No', '基金公司統編(CMoney)', 'Y')

Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '代號', 'text', 'Fundid', '基金代號(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '名稱', 'text', 'cname', '基金公司名稱(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '英文名稱', 'text', 'ename', '基金公司英文名稱(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , 'ISIN Code', 'text', 'isin', 'ISIN Code(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '投信代碼', 'text', 'sitid', '投信公司代碼(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '投信名稱', 'text', 'sitcname', '投信名稱(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '成立日期', 'date', 'issueDate', '成立日期(CMoney)', 'Y')
Insert into CMoney.dbo.Job_ColumnMapping ( jobID, cmColumn, colType, nsColumn, cmColumnDes, f_CmUse )
Values ( 81 , '成立規模(億)', 'decimal', 'fundsize', '成立規模(CMoney)', 'Y')

